"""empty message

Revision ID: c52af341931e
Revises: 
Create Date: 2023-06-16 11:08:25.951225

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c52af341931e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mst_tbl_product')
    op.drop_table('tbl_order')
    op.drop_table('tbl_order_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tbl_order_detail',
    sa.Column('order_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_detail_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('product_code', sa.VARCHAR(length=6), autoincrement=False, nullable=True),
    sa.Column('order_quantity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_delete', postgresql.BIT(length=1), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_no', name='tbl_order_detail_pkey')
    )
    op.create_table('tbl_order',
    sa.Column('order_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_code', sa.VARCHAR(length=3), autoincrement=False, nullable=False),
    sa.Column('supplier_code', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('employee_code', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('update_employee_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_delete', postgresql.BIT(length=1), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('order_no', name='tbl_order_pkey')
    )
    op.create_table('mst_tbl_product',
    sa.Column('product_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('product_name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('category_code', sa.VARCHAR(length=3), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('unit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_delete', postgresql.BIT(length=1), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('updated_at', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('product_code', name='mst_tbl_product_pkey')
    )
    # ### end Alembic commands ###
